import * as Scrivito from "scrivito";
const allowedContent = [
  "AddressWidget",
  "BlogOverviewWidget",
  "BoxWidget",
  "ButtonWidget",
  "CarouselWidget",
  "ColumnContainerWidget",
  "DividerWidget",
  "EventOverviewWidget",
  "FactWidget",
  "FeaturePanelWidget",
  "FormCheckboxWidget",
  "FormDateWidget",
  "FormHiddenFieldWidget",
  "FormConditionalContainerWidget",
  "FormInputFieldWidget",
  "FormRatingWidget",
  "FormSelectWidget",
  "GalleryWidget",
  "GoogleMapsWidget",
  "GroupWidget",
  "HeadlineWidget",
  "IconContainerWidget",
  "IconWidget",
  "ImageWidget",
  "JobOverviewWidget",
  "LinkContainerWidget",
  "PricingWidget",
  "SpaceWidget",
  "TableWidget",
  "TestimonialSliderWidget",
  "TextWidget",
  "ThumbnailGalleryWidget",
  "TickListWidget",
  "VideoWidget",
  "VimeoVideoWidget",
  "YoutubeVideoWidget",
];

export const FormStepWidget = Scrivito.provideWidgetClass("FormStepWidget", {
  onlyInside: "FormContainerWidget",
  attributes: {
    items: ["widgetlist", { only: allowedContent }],
    stepNumber: "integer",
    isActive: "boolean",
  },
});
