import * as Scrivito from "scrivito";
const singleStepAllowedContent = [
  "AddressWidget",
  "BlogOverviewWidget",
  "BoxWidget",
  "ButtonWidget",
  "CarouselWidget",
  "ColumnContainerWidget",
  "DividerWidget",
  "EventOverviewWidget",
  "FactWidget",
  "FeaturePanelWidget",
  "FormCheckboxWidget",
  "FormDateWidget",
  "FormHiddenFieldWidget",
  "FormConditionalContainerWidget",
  "FormInputFieldWidget",
  "FormRatingWidget",
  "FormSelectWidget",
  "GalleryWidget",
  "GoogleMapsWidget",
  "GroupWidget",
  "HeadlineWidget",
  "IconContainerWidget",
  "IconWidget",
  "ImageWidget",
  "JobOverviewWidget",
  "LinkContainerWidget",
  "PricingWidget",
  "SpaceWidget",
  "TableWidget",
  "TestimonialSliderWidget",
  "TextWidget",
  "ThumbnailGalleryWidget",
  "TickListWidget",
  "VideoWidget",
  "VimeoVideoWidget",
  "YoutubeVideoWidget",
];
export const FormContainerWidget = Scrivito.provideWidgetClass(
  "FormContainerWidget",
  {
    attributes: {
      singleStepContent: ["widgetlist", { only: singleStepAllowedContent }],
      formId: "string",
      failedMessage: "string",
      submittedMessage: "string",
      submittingMessage: "string",
      hiddenFields: ["widgetlist", { only: "FormHiddenFieldWidget" }],
      formType: [
        "enum",
        {
          values: ["single-step", "multi-step"],
        },
      ],
      steps: ["widgetlist", { only: "FormStepWidget" }],
      forwardButtonText: "string",
      backwardButtonText: "string",
      submitButtonText: "string",
      showBorder: "boolean",
      singleSubmitButtonAlignment: [
        "enum",
        {
          values: ["left", "text-center", "text-end", "block"],
        },
      ],
    },
    extractTextAttributes: ["singleStepContent", "steps"],
  }
);
